### ISSUE TITLE
EFI firmware error in virt-manager - VM Configuration

### ISSUE THREAD

**Issue by passbe** [infokiller/win10-vm#3]
Thank you for this wonderful information. I have a Windows 11 that is boot looping after initial install and believe the subsequent security GPOs are causing the issue with missing keys. I've run your `build.sh` script and gone to update my virtual machine within virt-manager and received the following error:

![image](https://github.com/infokiller/win10-vm/assets/306256/d83871d2-82c6-4e99-bcc3-fd4aeec14119)

Would you be willing to share your virtual machine configuration so I can test any differences and understand why virt-manager/qemu isn't happy?

**Comment by infokiller** [comment]
Hey @passbe I uploaded my Windows 11 libvirt config to a gist: https://gist.github.com/infokiller/00be381aa1d925a4f73bf03faaacd6d1

**Comment by passbe** [comment]
Thank you @infokiller
